
[build-system]
requires = ["hatchling"]              
build-backend = "hatchling.build"


[project]
name = "phlsM3U8_downner"         
version = "0.1.4"                    
description = "Async HLS/m3u8 downloader with AES-128 decryption and ffmpeg merging"
readme = "README.md"                  
license = "MIT"
license-files = ["LICENSE"]          
requires-python = ">=3.10"            
authors = [{ name = "AP945" }]
keywords = ["hls", "m3u8", "downloader", "ffmpeg", "aes-128","segment"]
classifiers = [
    "Natural Language :: Chinese (Simplified)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Video",
]

# 依赖

dependencies = [
    "aiohttp",        # main.py / Download_Manage.py
    "aiofiles",       # Writefile
    "tenacity",       # 重试
    "rich",           # 进度条
    "pycryptodome",   # Cryptodome
    "ffmpeg-python",  # _Converter
]

[project.urls]
Homepage = "https://github.com/ap945/phlsM3U8_downner"

[tool.hatch.build.targets.wheel]
packages = ["phlsM3U8_downner"]
